
SUBROUTINE MLS_HIGHERORDERDEFGRADIENT(NNO,NDI,XD,F,F2,DFF,DFF2)
  USE BASFUN
  IMPLICIT REAL(8)(A-H,O-Z)
  REAL(8),DIMENSION(NDI,NNO)::XO,XD
  REAL(8),DIMENSION(NDI,NDI)::F
  REAL(8),DIMENSION(NDI,NDI,NDI)::F2
  REAL(8),DIMENSION(NDI,NNO)::DFF,DFCC
  REAL(8),DIMENSION(NDI,NDI,NNO)::DFF2,DF2CC
  F=0.0D00
  F2=0.0D00
  DO I=1,NDI
     DO J=1,NDI
        DO L=1,NNO
           F(I,J)=F(I,J)+DFF(J,L)*XD(I,L)
           DO K=1,NDI
              F2(I,J,K)=F2(I,J,K)+DFF2(J,K,L)*XD(I,L)
           END DO
        END DO
     END DO
  END DO
END SUBROUTINE MLS_HIGHERORDERDEFGRADIENT
!!$
SUBROUTINE MLS_HIGHERORDERSTRAINS(NDI,F,F2,E,E2)
  USE BASFUN
  IMPLICIT REAL(8)(A-H,O-Z)
  REAL(8),DIMENSION(NDI,NDI)::E,F
  REAL(8),DIMENSION(NDI,NDI,NDI)::E2,F2
  E=0.0D00
  E2=0.0D00
  DO I=1,NDI
     DO J=1,NDI
        DO N=1,NDI
           E(I,J)=E(I,J)+F(N,I)*F(N,J)
           DO L=1,NDI
              E2(I,J,L)=E2(I,J,L)+(F2(N,I,L)*F(N,J)+F(N,I)*F2(N,J,L))*0.5D00
           END DO
        END DO
     END DO
  END DO
  DO i=1,ndi
     DO j=1,ndi
        E(I,J)=0.5D00*E(I,J)-0.5D00*DELTAK(I,J)
     END DO
  END DO
END SUBROUTINE MLS_HIGHERORDERSTRAINS
!
